# Generated by Django 4.1.7 on 2023-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/895/895351.png?w=740&t=st=1682622239~exp=1682622839~hmac=79711d54554e108dea4b360d4fd6a6ea317e0d4481c446b75eb1094e77e551b2', max_length=500),
        ),
    ]
