# Generated by Django 4.1.7 on 2023-05-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://media4.giphy.com/media/26BRqPg05olzXG1bi/giphy.gif?cid=ecf05e47w7pu1wqd50xlfonrwvc45iat93zr1jlcmg39ft43&ep=v1_gifs_search&rid=giphy.gif&ct=g', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
