# Generated by Django 4.1.7 on 2023-05-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_image_alter_item_item_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='https://media4.giphy.com/media/26BRqPg05olzXG1bi/giphy.gif?cid=ecf05e47w7pu1wqd50xlfonrwvc45iat93zr1jlcmg39ft43&ep=v1_gifs_search&rid=giphy.gif&ct=g', upload_to='posts'),
        ),
    ]
